### PR TITLE
Update meta.yaml

### PR DESCRIPTION
**Pull request by jhamman**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jhamman** [comment]
cc @lesteve @guillaumeeb

**Comment by lesteve** [comment]
This looks good to me, thanks a lot!

**Comment by jakirkham** [comment]
Does this mean we need to pull some packages?

**Comment by jhamman** [comment]
@jakirkham - what do you mean?

**Comment by jakirkham** [comment]
Based on this PR, I'm guessing the packages with build number 0 have incorrect dependencies and so we should pull them. Does that sound right or no?

**Comment by jhamman** [comment]
@jakirkham - I see what you mean. I'm not too worried about having the first build out there but if its easy to remove them, we can certainly do that. 

I'm going to merge this now.

**Comment by mrocklin** [comment]
The challenge is that if someone tries to conda install dask-jobqueue with
an older version of Dask conda will happily give them that bad package.

**Comment by lesteve** [comment]
Ah good point @mrocklin! 

I did not know you could remove packages from conda-forge, but if that's possible, that'd be great!

**Comment by jakirkham** [comment]
Not remove, but marking them as broken. Happy to do that if you like. Just let me know.

**Comment by lesteve** [comment]
Assuming that this is not too much work (say less than 15 minutes), that would be really great indeed!

The package we would like to mark as broken is `dask-jobqueue=0.6.1=py_0`:

```
 ❯ conda search dask-jobqueue=0.6.1=py_0 -c conda-forge --info
Loading channels: done
dask-jobqueue 0.6.1 py_0
------------------------
file name   : dask-jobqueue-0.6.1-py_0.tar.bz2
name        : dask-jobqueue
version     : 0.6.1
build       : py_0
build number: 0
size        : 28 KB
license     : BSD 3-Clause
subdir      : noarch
url         : https://conda.anaconda.org/conda-forge/noarch/dask-jobqueue-0.6.1-py_0.tar.bz2
md5         : 7593a3b70e0a44d4682cc387a70671ec
timestamp   : 2019-07-25 17:03:34 UTC
dependencies: 
  - dask >=1.2.0
  - distributed >=1.27
  - docrep
  - python >=3.5
```

**Comment by jakirkham** [comment]
Sure, done. Please re-check that I got the right one.

Screen Shot 2019-07-30 at 1 51 00 PM

**Comment by lesteve** [comment]
You got the right one, thanks a lot for this!

**Pull request merged**
